<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<div class="container-fluid">
	<div class="d-sm-flex align-items-center justify-content-between mb-4"><div><h1 class="h3 mb-1 text-gray-800">Sejarah</h1><p class="mb-0 text-gray-600">Kelola sejarah perusahaan sebagai satu dokumen lengkap.</p></div><button type="button" class="btn btn-sm btn-primary" id="btn-tambah-modal"><i class="fas fa-plus mr-1"></i> Tambah</button></div>
	<div class="card shadow mb-4"><div class="card-header py-3"><h6 class="m-0 font-weight-bold text-primary">Data Sejarah</h6></div><div class="card-body"><div class="row"><div class="col-md-4"><div class="input-group mb-3"><input type="text" class="form-control" id="cari" placeholder="Cari sejarah"><div class="input-group-append"><span class="input-group-text bg-primary text-white"><i class="fas fa-search"></i></span></div></div></div></div><div id="data_sejarah"></div><div class="d-flex justify-content-between align-items-center mt-3"><div id="pagination"></div><div class="d-flex align-items-center"><label class="mb-0 mr-2">Tampilkan</label><select class="form-control form-control-sm" id="jumlah_data" style="width:80px"><option value="10">10</option><option value="25">25</option></select><span class="ml-2">entri</span></div></div></div></div>
</div>

<div class="modal fade" id="modalTambah" tabindex="-1" role="dialog" aria-hidden="true"><div class="modal-dialog modal-xl" role="document"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Tambah Sejarah</h5><button class="close" type="button" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body"><form id="form-tambah"><div class="form-group"><label>Judul Sejarah</label><input class="form-control" name="judul" required></div><div class="form-group"><label>Isi Sejarah</label><div id="editorKontenTambah" style="min-height:320px"></div><input type="hidden" name="konten"></div><div class="form-group"><label>Status</label><select class="form-control" name="status"><option value="aktif">Aktif</option><option value="nonaktif">Nonaktif</option></select></div><div class="alert alert-danger d-none form-message"></div></form></div><div class="modal-footer"><button class="btn btn-secondary" type="button" data-dismiss="modal">Batal</button><button class="btn btn-primary" type="button" id="btn-simpan">Simpan</button></div></div></div></div>

<div class="modal fade" id="modalEdit" tabindex="-1" role="dialog" aria-hidden="true"><div class="modal-dialog modal-xl" role="document"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Edit Sejarah</h5><button class="close" type="button" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body"><form id="form-edit"><input type="hidden" name="id_sejarah"><div class="form-group"><label>Judul Sejarah</label><input class="form-control" name="judul" required></div><div class="form-group"><label>Isi Sejarah</label><div id="editorKontenEdit" style="min-height:320px"></div><input type="hidden" name="konten"></div><div class="form-group"><label>Status</label><select class="form-control" name="status"><option value="aktif">Aktif</option><option value="nonaktif">Nonaktif</option></select></div><div class="alert alert-danger d-none form-message"></div></form></div><div class="modal-footer"><button class="btn btn-secondary" type="button" data-dismiss="modal">Batal</button><button class="btn btn-primary" type="button" id="btn-update">Simpan Perubahan</button></div></div></div></div>

<script>
var quillSejarahTambah, quillSejarahEdit;
document.addEventListener('DOMContentLoaded',function(){var options={theme:'snow',modules:{toolbar:[['bold','italic','underline','strike'],[{header:[1,2,3,false]}],[{list:'ordered'},{list:'bullet'}],[{align:[]}],['blockquote','link'],['clean']]}};quillSejarahTambah=new Quill('#editorKontenTambah',options);quillSejarahEdit=new Quill('#editorKontenEdit',options);$('#cari').on('keyup',sejarah);$('#jumlah_data').on('change',function(){paging($('#data_sejarah .card-sejarah'),parseInt(this.value,10));});$('#btn-tambah-modal').on('click',function(){$('#form-tambah')[0].reset();quillSejarahTambah.setText('');$('#modalTambah').modal('show');});$('#btn-simpan').on('click',function(){simpanSejarah('#form-tambah',quillSejarahTambah,'<?php echo site_url('admin/sejarah/tambah'); ?>','#modalTambah',this);});$('#btn-update').on('click',function(){simpanSejarah('#form-edit',quillSejarahEdit,'<?php echo site_url('admin/sejarah/edit'); ?>','#modalEdit',this);});sejarah();});
function escapeHtml(value){return String(value||'').replace(/[&<>"']/g,function(item){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[item];});}
function plainText(html){var node=document.createElement('div');node.innerHTML=html||'';return(node.textContent||'').trim();}
function sejarah(){$.ajax({url:'<?php echo site_url('admin/sejarah/sejarah_result'); ?>',type:'POST',dataType:'json',data:{search:$('#cari').val()},success:function(result){var rows=result.data||[],html='';$('#btn-tambah-modal').toggleClass('d-none',result.has_data===true);if(!rows.length)html='<div class="alert alert-light border text-center mb-0">Belum ada data sejarah.</div>';else rows.forEach(function(item){html+=`<div class="card-sejarah border rounded p-3 mb-3"><div class="d-flex flex-column flex-md-row justify-content-between"><div class="pr-md-4"><h5 class="text-gray-900 mb-2">${escapeHtml(item.judul)}</h5><p class="mb-0 text-muted">${escapeHtml(plainText(item.konten).slice(0,260))}</p></div><div class="admin-record-meta mt-3 mt-md-0"><span class="badge badge-${item.status==='aktif'?'success':'secondary'}">${escapeHtml(item.status)}</span><div class="admin-action-group"><button class="btn btn-sm btn-warning" onclick="editSejarah(${item.id_sejarah})"><i class="fas fa-edit"></i></button><button class="btn btn-sm btn-danger" onclick="hapusSejarah(${item.id_sejarah})"><i class="fas fa-trash"></i></button></div></div></div></div>`;});$('#data_sejarah').html(html);paging($('#data_sejarah .card-sejarah'),parseInt($('#jumlah_data').val(),10));}});}
function simpanSejarah(formSelector,editor,url,modalSelector,button){var form=$(formSelector),message=form.find('.form-message');form.find('[name="konten"]').val(editor.getText().trim()?editor.root.innerHTML:'');if(!form.find('[name="judul"]').val().trim()||!form.find('[name="konten"]').val()){message.removeClass('d-none').text('Judul dan isi sejarah wajib diisi.');return;}$(button).prop('disabled',true);$.ajax({url:url,type:'POST',data:form.serialize(),dataType:'json',success:function(result){if(result.status){$(modalSelector).modal('hide');sejarah();}else message.removeClass('d-none').text(result.message||'Data gagal disimpan.');},complete:function(){$(button).prop('disabled',false);}});}
function editSejarah(id){$.ajax({url:'<?php echo site_url('admin/sejarah/sejarah_edit'); ?>',type:'POST',dataType:'json',data:{id_sejarah:id},success:function(result){if(!result.status)return;var item=result.data;$('#form-edit [name="id_sejarah"]').val(item.id_sejarah);$('#form-edit [name="judul"]').val(item.judul);$('#form-edit [name="status"]').val(item.status);quillSejarahEdit.setText('');quillSejarahEdit.clipboard.dangerouslyPasteHTML(item.konten||'');$('#modalEdit').modal('show');}});}
function hapusSejarah(id){if(!confirm('Hapus data sejarah ini?'))return;$.ajax({url:'<?php echo site_url('admin/sejarah/hapus'); ?>/'+id,type:'POST',dataType:'json',success:sejarah});}
function paging($selector,jumlahTampil){$('#pagination').empty();if(!$selector.length)return;window.tp=new Pagination('#pagination',{itemsCount:$selector.length,pageSize:jumlahTampil||10,onPageChange:function(page){var start=page.pageSize*(page.currentPage-1),end=start+page.pageSize;$selector.hide();for(var i=start;i<end;i++)$selector.eq(i).show();}});}
</script>
