<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<div class="container-fluid">
	<div class="d-sm-flex align-items-center justify-content-between mb-4"><div><h1 class="h3 mb-1 text-gray-800">Visi dan Misi</h1><p class="mb-0 text-gray-600">Kelola visi dan misi perusahaan sebagai satu dokumen.</p></div><button type="button" class="btn btn-sm btn-primary" id="btn-tambah-modal"><i class="fas fa-plus mr-1"></i> Tambah</button></div>
	<div class="card shadow mb-4"><div class="card-header py-3"><h6 class="m-0 font-weight-bold text-primary">Data Visi dan Misi</h6></div><div class="card-body">
		<div class="row"><div class="col-md-4"><div class="input-group mb-3"><input type="text" class="form-control" id="cari" placeholder="Cari isi visi atau misi"><div class="input-group-append"><span class="input-group-text bg-primary text-white"><i class="fas fa-search"></i></span></div></div></div></div>
		<div id="data_visi_misi"></div><div class="d-flex justify-content-between align-items-center mt-3"><div id="pagination"></div><div class="d-flex align-items-center"><label class="mb-0 mr-2">Tampilkan</label><select class="form-control form-control-sm" id="jumlah_data" style="width:80px"><option value="10">10</option><option value="25">25</option></select><span class="ml-2">entri</span></div></div>
	</div></div>
</div>

<div class="modal fade" id="modalTambah" tabindex="-1" role="dialog" aria-hidden="true"><div class="modal-dialog modal-xl" role="document"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Tambah Visi dan Misi</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body"><form id="form-tambah"><div class="form-group"><label>Visi</label><div id="editorVisiTambah" style="min-height:180px"></div><input type="hidden" name="visi"></div><div class="form-group"><label>Misi</label><div id="editorMisiTambah" style="min-height:240px"></div><input type="hidden" name="misi"></div><div class="form-group"><label>Status</label><select class="form-control" name="status"><option value="aktif">Aktif</option><option value="nonaktif">Nonaktif</option></select></div><div class="alert alert-danger d-none form-message"></div></form></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button><button type="button" class="btn btn-primary" id="btn-simpan">Simpan</button></div></div></div></div>

<div class="modal fade" id="modalEdit" tabindex="-1" role="dialog" aria-hidden="true"><div class="modal-dialog modal-xl" role="document"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Edit Visi dan Misi</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body"><form id="form-edit"><input type="hidden" name="id_visi_misi"><div class="form-group"><label>Visi</label><div id="editorVisiEdit" style="min-height:180px"></div><input type="hidden" name="visi"></div><div class="form-group"><label>Misi</label><div id="editorMisiEdit" style="min-height:240px"></div><input type="hidden" name="misi"></div><div class="form-group"><label>Status</label><select class="form-control" name="status"><option value="aktif">Aktif</option><option value="nonaktif">Nonaktif</option></select></div><div class="alert alert-danger d-none form-message"></div></form></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button><button type="button" class="btn btn-primary" id="btn-update">Simpan Perubahan</button></div></div></div></div>

<script>
var quillVisiTambah, quillMisiTambah, quillVisiEdit, quillMisiEdit;
document.addEventListener('DOMContentLoaded', function () {
	var options = {theme:'snow', modules:{toolbar:[['bold','italic','underline','strike'],[{header:[1,2,3,false]}],[{list:'ordered'},{list:'bullet'}],[{align:[]}],['blockquote','link'],['clean']]}};
	quillVisiTambah = new Quill('#editorVisiTambah', options); quillMisiTambah = new Quill('#editorMisiTambah', options); quillVisiEdit = new Quill('#editorVisiEdit', options); quillMisiEdit = new Quill('#editorMisiEdit', options);
	$('#cari').on('keyup', visiMisi); $('#jumlah_data').on('change', function () { paging($('#data_visi_misi .card-visi-misi'), parseInt(this.value, 10)); });
	$('#btn-tambah-modal').on('click', function () { quillVisiTambah.setText(''); quillMisiTambah.setText(''); $('#form-tambah')[0].reset(); $('#modalTambah').modal('show'); });
	$('#btn-simpan').on('click', function () { simpanVisiMisi('#form-tambah', quillVisiTambah, quillMisiTambah, '<?php echo site_url('admin/visi_misi/tambah'); ?>', '#modalTambah', this); });
	$('#btn-update').on('click', function () { simpanVisiMisi('#form-edit', quillVisiEdit, quillMisiEdit, '<?php echo site_url('admin/visi_misi/edit'); ?>', '#modalEdit', this); });
	visiMisi();
});
function escapeHtml(value){return String(value||'').replace(/[&<>"']/g,function(item){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[item];});}
function plainText(html){var node=document.createElement('div');node.innerHTML=html||'';return(node.textContent||'').trim();}
function visiMisi(){ $.ajax({url:'<?php echo site_url('admin/visi_misi/visi_misi_result'); ?>',type:'POST',dataType:'json',data:{search:$('#cari').val()},success:function(result){var rows=result.data||[],html='';$('#btn-tambah-modal').toggleClass('d-none',result.has_data===true);if(!rows.length)html='<div class="alert alert-light border text-center mb-0">Belum ada data visi dan misi.</div>';else rows.forEach(function(item){html+=`<div class="card-visi-misi border rounded p-3 mb-3"><div class="d-flex flex-column flex-md-row justify-content-between"><div class="pr-md-4"><h5 class="text-gray-900">Visi</h5><p>${escapeHtml(plainText(item.visi).slice(0,180))}</p><h5 class="text-gray-900">Misi</h5><p class="mb-0">${escapeHtml(plainText(item.misi).slice(0,220))}</p></div><div class="admin-record-meta mt-3 mt-md-0"><span class="badge badge-${item.status==='aktif'?'success':'secondary'}">${escapeHtml(item.status)}</span><div class="admin-action-group"><button class="btn btn-sm btn-warning" onclick="editVisiMisi(${item.id_visi_misi})"><i class="fas fa-edit"></i></button><button class="btn btn-sm btn-danger" onclick="hapusVisiMisi(${item.id_visi_misi})"><i class="fas fa-trash"></i></button></div></div></div></div>`;});$('#data_visi_misi').html(html);paging($('#data_visi_misi .card-visi-misi'),parseInt($('#jumlah_data').val(),10));}}); }
function simpanVisiMisi(formSelector,visiEditor,misiEditor,url,modalSelector,button){var form=$(formSelector),message=form.find('.form-message');form.find('[name="visi"]').val(visiEditor.getText().trim()?visiEditor.root.innerHTML:'');form.find('[name="misi"]').val(misiEditor.getText().trim()?misiEditor.root.innerHTML:'');if(!form.find('[name="visi"]').val()||!form.find('[name="misi"]').val()){message.removeClass('d-none').text('Visi dan misi wajib diisi.');return;}$(button).prop('disabled',true);$.ajax({url:url,type:'POST',data:form.serialize(),dataType:'json',success:function(result){if(result.status){$(modalSelector).modal('hide');visiMisi();}else message.removeClass('d-none').text(result.message||'Data gagal disimpan.');},complete:function(){$(button).prop('disabled',false);}});}
function editVisiMisi(id){$.ajax({url:'<?php echo site_url('admin/visi_misi/visi_misi_edit'); ?>',type:'POST',dataType:'json',data:{id_visi_misi:id},success:function(result){if(!result.status)return;var item=result.data;$('#form-edit [name="id_visi_misi"]').val(item.id_visi_misi);$('#form-edit [name="status"]').val(item.status);quillVisiEdit.setText('');quillMisiEdit.setText('');quillVisiEdit.clipboard.dangerouslyPasteHTML(item.visi||'');quillMisiEdit.clipboard.dangerouslyPasteHTML(item.misi||'');$('#modalEdit').modal('show');}});}
function hapusVisiMisi(id){if(!confirm('Hapus data visi dan misi ini?'))return;$.ajax({url:'<?php echo site_url('admin/visi_misi/hapus'); ?>/'+id,type:'POST',dataType:'json',success:visiMisi});}
function paging($selector,jumlahTampil){$('#pagination').empty();if(!$selector.length)return;window.tp=new Pagination('#pagination',{itemsCount:$selector.length,pageSize:jumlahTampil||10,onPageChange:function(page){var start=page.pageSize*(page.currentPage-1),end=start+page.pageSize;$selector.hide();for(var i=start;i<end;i++)$selector.eq(i).show();}});}
</script>
