<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<div class="container-fluid">
	<div class="d-sm-flex align-items-center justify-content-between mb-4"><h1 class="h3 mb-0 text-gray-800">Edit Admin User</h1><a href="<?php echo site_url('admin/admin_user'); ?>" class="btn btn-sm btn-secondary"><i class="fas fa-arrow-left mr-1"></i> Kembali</a></div>
	<div class="card shadow mb-4"><div class="card-body">
		<form id="formEditAdmin" enctype="multipart/form-data"><input type="hidden" name="id_admin" value="<?php echo (int) $item['id_admin']; ?>">
			<div class="row"><div class="col-md-6"><div class="form-group"><label>Nama Lengkap</label><input type="text" class="form-control" name="nama" required value="<?php echo htmlspecialchars($item['nama'], ENT_QUOTES, 'UTF-8'); ?>"></div></div><div class="col-md-6"><div class="form-group"><label>Username</label><input type="text" class="form-control" name="username" required value="<?php echo htmlspecialchars($item['username'], ENT_QUOTES, 'UTF-8'); ?>" autocomplete="off"></div></div></div>
			<div class="row"><div class="col-md-8"><div class="form-group"><label>Password Baru</label><input type="password" class="form-control" name="password_hash" minlength="8" autocomplete="new-password"><small class="form-text text-muted">Kosongkan jika password tidak diganti.</small></div></div><div class="col-md-4"><div class="form-group"><label>Status</label><select class="form-control" name="status"><option value="aktif" <?php echo $item['status'] === 'aktif' ? 'selected' : ''; ?>>Aktif</option><option value="nonaktif" <?php echo $item['status'] === 'nonaktif' ? 'selected' : ''; ?>>Nonaktif</option></select></div></div></div>
			<div class="form-group"><label>Foto Profil</label><input type="file" class="dropify" name="foto" accept="image/jpeg,image/png,image/webp" data-max-file-size="4M" <?php echo !empty($item['foto']) ? 'data-default-file="' . base_url($item['foto']) . '"' : ''; ?>><small class="form-text text-muted">Biarkan foto lama jika tidak ingin menggantinya.</small></div>
			<div class="alert alert-danger d-none" id="pesanAdmin"></div><button type="submit" class="btn btn-primary" id="simpanAdmin"><i class="fas fa-save mr-1"></i> Simpan Perubahan</button>
		</form>
	</div></div>
</div>
<script>
document.addEventListener('DOMContentLoaded',function(){$('.dropify').dropify({messages:{default:'Seret foto atau klik untuk memilih',replace:'Seret foto atau klik untuk mengganti',remove:'Hapus',error:'Terjadi kesalahan'}});$('#formEditAdmin').on('submit',function(event){event.preventDefault();var button=$('#simpanAdmin').prop('disabled',true);$('#pesanAdmin').addClass('d-none');$.ajax({url:'<?php echo site_url('admin/admin_user/edit'); ?>',type:'POST',data:new FormData(this),processData:false,contentType:false,dataType:'json',success:function(result){if(result.status)window.location.href='<?php echo site_url('admin/admin_user'); ?>';else $('#pesanAdmin').removeClass('d-none').text(result.message||'Data gagal diperbarui.');},error:function(){$('#pesanAdmin').removeClass('d-none').text('Terjadi kesalahan saat memperbarui data.');},complete:function(){button.prop('disabled',false);}});});});
</script>
